[[constraint]]
  name = "github.com/apiheat/akamai-cli-common"
  version = "^2.0.0"

[[constraint]]
  name = "github.com/apiheat/go-edgegrid"
  version = "^5.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"